// Opciones de marcas de vehículos
export const brandOptions = [
  { label: "ABARTH", value: "ABARTH" },
  { label: "AC", value: "AC" },
  { label: "ACURA", value: "ACURA" },
  { label: "AIXAM", value: "AIXAM" },
  { label: "ALFA ROMEO", value: "ALFA ROMEO" },
  { label: "ALPINA", value: "ALPINA" },
  { label: "ALPINE", value: "ALPINE" },
  { label: "ASTON MARTIN", value: "ASTON MARTIN" },
  { label: "AUDI", value: "AUDI" },
  { label: "BMW", value: "BMW" },
  { label: "CHEVROLET", value: "CHEVROLET" },
  { label: "CITROËN", value: "CITROËN" },
  { label: "DACIA", value: "DACIA" },
  { label: "DAEWOO", value: "DAEWOO" },
  { label: "DAIHATSU", value: "DAIHATSU" },
  { label: "DODGE", value: "DODGE" },
  { label: "FIAT", value: "FIAT" },
  { label: "FORD", value: "FORD" },
  { label: "HONDA", value: "HONDA" },
  { label: "HYUNDAI", value: "HYUNDAI" },
  { label: "JAGUAR", value: "JAGUAR" },
  { label: "JEEP", value: "JEEP" },
  { label: "KIA", value: "KIA" },
  { label: "LANCIA", value: "LANCIA" },
  { label: "LAND ROVER", value: "LAND ROVER" },
  { label: "LEXUS", value: "LEXUS" },
  { label: "MAZDA", value: "MAZDA" },
  { label: "MERCEDES-BENZ", value: "MERCEDES-BENZ" },
  { label: "MG", value: "MG" },
  { label: "MINI", value: "MINI" },
  { label: "MITSUBISHI", value: "MITSUBISHI" },
  { label: "NISSAN", value: "NISSAN" },
  { label: "OPEL", value: "OPEL" },
  { label: "PEUGEOT", value: "PEUGEOT" },
  { label: "PORSCHE", value: "PORSCHE" },
  { label: "RENAULT", value: "RENAULT" },
  { label: "ROVER", value: "ROVER" },
  { label: "SAAB", value: "SAAB" },
  { label: "SEAT", value: "SEAT" },
  { label: "SKODA", value: "SKODA" },
  { label: "SMART", value: "SMART" },
  { label: "SSANGYONG", value: "SSANGYONG" },
  { label: "SUBARU", value: "SUBARU" },
  { label: "SUZUKI", value: "SUZUKI" },
  { label: "TESLA", value: "TESLA" },
  { label: "TOYOTA", value: "TOYOTA" },
  { label: "VOLKSWAGEN", value: "VOLKSWAGEN" },
  { label: "VOLVO", value: "VOLVO" },
  { label: "OTROS", value: "OTROS" },
];
